name: Sample Workflow
on:
  push: # enabling push event on master branch to fire the workflow
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its subdirectory
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -alR
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files # this steps won't be showing any files as we didn't checkout our codes
        run: |
          pwd
          ls -alR

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Thank you
          VAR2: very much.
          VAR3: Enjoy !!!